### ISSUE TITLE
Got stuck :'(

### ISSUE THREAD

**Issue by AriaFallah** [ayebear/project-square#28]
My poor little square was doomed to spend eternity in that chamber.

![screen shot 2016-05-02 at 7 25 24 pm](https://cloud.githubusercontent.com/assets/9424976/14970984/b3f767a4-109b-11e6-82e1-5ef71ac459e7.png)

**Comment by ayebear** [comment]
This is just the beginning, wait until you have to time travel and setup
magnetic fields to move blocks around :)

**Comment by ayebear** [comment]
Puzzles are now completely non-linear in latest "cloning" branch.
